### ISSUE TITLE
Cannot createdb on README.md following quick install

### ISSUE THREAD

**Issue by trolando** [jonge-democraten/website#58]
Get this error:

(env)tom@trolla:~/jd/website$ python website/manage.py createdb
/home/tom/jd/website/env/lib/python3.4/site-packages/mezzanine/core/managers.py:194: RemovedInDjango18Warning: `SearchableManager.get_query_set` method should be renamed `get_queryset`.
  class SearchableManager(Manager):

/home/tom/jd/website/env/lib/python3.4/site-packages/mezzanine/core/managers.py:326: RemovedInDjango18Warning: `CurrentSiteManager.get_query_set` method should be renamed `get_queryset`.
  class CurrentSiteManager(DjangoCSM):

/home/tom/jd/website/env/lib/python3.4/site-packages/django/contrib/comments/__init__.py:13: RemovedInDjango18Warning: django.contrib.comments is deprecated and will be removed before Django 1.8.
  warnings.warn("django.contrib.comments is deprecated and will be removed before Django 1.8.", RemovedInDjango18Warning)

Traceback (most recent call last):
  File "/home/tom/jd/website/env/lib/python3.4/site-packages/mezzanine/conf/__init__.py", line 182, in __getattr__
    setting = registry[name]
KeyError: 'GRAPPELLI_INSTALLED'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "website/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/home/tom/jd/website/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/tom/jd/website/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/tom/jd/website/env/lib/python3.4/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/tom/jd/website/env/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/tom/jd/website/env/lib/python3.4/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/tom/jd/website/env/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/tom/jd/website/env/lib/python3.4/site-packages/mezzanine/forms/models.py", line 10, in <module>
    from mezzanine.forms import fields
  File "/home/tom/jd/website/env/lib/python3.4/site-packages/mezzanine/forms/fields.py", line 9, in <module>
    from mezzanine.core.forms import SplitSelectDateTimeWidget
  File "/home/tom/jd/website/env/lib/python3.4/site-packages/mezzanine/core/forms.py", line 40, in <module>
    if settings.GRAPPELLI_INSTALLED:
  File "/home/tom/jd/website/env/lib/python3.4/site-packages/mezzanine/conf/__init__.py", line 184, in __getattr__
    return getattr(django_settings, name)
  File "/home/tom/jd/website/env/lib/python3.4/site-packages/django/conf/__init__.py", line 47, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'GRAPPELLI_INSTALLED'

**Comment by floort** [comment]
Have you tried building with a clean env?

**Comment by trolando** [comment]
Ah, I see. I did start completely clean (after checkout) but the first
build_env.sh failed because libpython3-dev was not installed on my Ubuntu
setup. I installed the libpython3-dev and reran build_env.sh, running into
the errors.
