### ISSUE TITLE
Commit e8beb69d888c4b01ee89b6db0f054914a2c5b16a is broken

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#68]
When I try to run ./build_env.sh on commit e8beb69d888c4b01ee89b6db0f054914a2c5b16a (currently the foremost commit in branch feature/hemres), I get an error:

```
  Installing extra requirements: 'egg'
Obtaining hemres from git+https://github.com/jonge-democraten/hemres@master#egg=hemres (from -r requirements.txt (line 7))
  Cloning https://github.com/jonge-democraten/hemres (to master) to ./env/src/hemres
  Running setup.py (path:/home/pieter/Documents/JD/ICT/NieuweWebsite/website/env/src/hemres/setup.py) egg_info for package hemres
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/pieter/Documents/JD/ICT/NieuweWebsite/website/env/src/hemres/setup.py", line 6, in <module>
        packages=find_packages(include=['hemres*']),
    TypeError: find_packages() got an unexpected keyword argument 'include'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/pieter/Documents/JD/ICT/NieuweWebsite/website/env/src/hemres/setup.py", line 6, in <module>

    packages=find_packages(include=['hemres*']),

TypeError: find_packages() got an unexpected keyword argument 'include'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/pieter/Documents/JD/ICT/NieuweWebsite/website/env/src/hemres
Storing debug log for failure in /home/pieter/.pip/pip.log
```

Please fix.

**Comment by bartromgens** [comment]
I get the same error in the hemres branch. 

Removing the include from ```packages=find_packages()``` in the ```setup.py``` will probably fix this.

**Comment by trolando** [comment]
Does this have anything to do with the version of setup_tools?

**Comment by bartromgens** [comment]
> Does this have anything to do with the version of setup_tools?

Possibly. What version are you running? 

Related, what Python version are you using for Hemres?

**Comment by trolando** [comment]
I changed this btw to no longer require find_packages in my tree.

Not sure about the version. Python, I guess 3.4.

**Comment by bartromgens** [comment]
This is fixed for me. Thanks trolando!
